version: "3.8"

services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/mydb
    depends_on:
      - mongo
    volumes:
      - ./backend:/usr/src/app/backend
      - /usr/src/app/backend/node_modules

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "3001:4000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
