services:
  backend:
    image: ajaytemplar/assessment-backend:amd64
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/db
    depends_on:
      - mongo
    restart: always
    networks:
      - app-network

  frontend:
    image: ajaytemplar/assessment-frontend:amd64
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - BACKEND_URL=http://app-network:3000
    depends_on:
      - backend
    restart: always
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
